### ISSUE TITLE
9.3 Support not mentioned in Readme despite being implemented?

### ISSUE THREAD

**Issue by HageMaster3108** [lowedown/xConnectHelper#8]
Seemingly PR #7 has implemented Sitecore 9.3 compatibility, but the README.md doesn't mention it.
I was about to just send a PR with a README update but was unsure whether 9.3 compatibility is complete/ready?

**Comment by lowedown** [comment]
Thanks for the heads-up. The current release supports 9.3 - I've updated the readme.
