### ISSUE TITLE
Source code for 10.x version?

### ISSUE THREAD

**Issue by joshd-emergent** [lowedown/xConnectHelper#9]
The base repo looks to just have the source code for 9.3, though we have a release package for 10.x. Can that be updated?

Appreciate the work on this!

**Comment by lowedown** [comment]
9.3 source should be fully compatible with 10.x. Let me know if there are
any issues.

Josh Dinndorf ***@***.***> schrieb am Mi., 6. Juli 2022,
22:14:

**Comment by joshd-emergent** [comment]
@lowedown #10 I did add a pr to support this.

**Comment by lowedown** [comment]
Thanks Josh, I missed that bit. I'll test-run your changes and create a new 10.x Release asap
